### ISSUE TITLE
TypeError: Cannot read property 'suite' of undefined

### ISSUE THREAD

**Issue by MadaraUchiha** [lazd/karma-benchmark-reporter#3]
My test:

``` javascript
'use strict';

describe('Math', function() {
    describe('.random()', function() {
        it('should be between 0 and 1', function() {
            var actual = Math.random();
            expect(actual).toBeLessThan(1);
            expect(actual).toBeGreaterThan(0);
        });
    });
});
```

My karma.conf file:

``` javascript
module.exports = function (config) {
    'use strict';

    config.set({
        basePath: '',
        frameworks: [
            'jasmine'
        ],
        // list of files / patterns to load in the browser
        files: [
            {pattern: 'test/**/*.js', included: true}
        ],
        reporters: ['benchmark'],
        autoWatch: false,
        logLevel: config.LOG_DEBUG,
        browsers: [
            'Chrome'
        ],
        singleRun: true
    });
};
```

package.json:

```
  "dependencies": {
    "jasmine-core": "^2.3.4",
    "karma": "^0.13.10",
    "karma-benchmark-reporter": "^0.1.1",
    "karma-chrome-launcher": "^0.2.0",
    "karma-jasmine": "^0.3.6"
  }
```

Full stack trace:

```
Missing error handler on `socket`.
TypeError: Cannot read property 'suite' of undefined
    at specSuccess (/home/madara/projects/jasmine-benchmark-testing/node_modules/karma-benchmark-reporter/index.js:35:33)
    at onSpecComplete (/home/madara/projects/jasmine-benchmark-testing/node_modules/karma/lib/reporters/base.js:78:12)
    at null.<anonymous> (/home/madara/projects/jasmine-benchmark-testing/node_modules/karma/lib/events.js:13:22)
    at emitTwo (events.js:87:13)
    at emit (events.js:172:7)
    at onResult (/home/madara/projects/jasmine-benchmark-testing/node_modules/karma/lib/browser.js:216:13)
    at Array.forEach (native)
    at onResult (/home/madara/projects/jasmine-benchmark-testing/node_modules/karma/lib/browser.js:206:21)
    at Socket.<anonymous> (/home/madara/projects/jasmine-benchmark-testing/node_modules/karma/lib/events.js:13:22)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Socket.onevent (/home/madara/projects/jasmine-benchmark-testing/node_modules/karma/node_modules/socket.io/lib/socket.js:330:8)
    at Socket.onpacket (/home/madara/projects/jasmine-benchmark-testing/node_modules/karma/node_modules/socket.io/lib/socket.js:290:12)
    at Client.ondecoded (/home/madara/projects/jasmine-benchmark-testing/node_modules/karma/node_modules/socket.io/lib/client.js:193:14)
    at Decoder.Emitter.emit (/home/madara/projects/jasmine-benchmark-testing/node_modules/karma/node_modules/socket.io/node_modules/socket.io-parser/node_modules/component-emitter/index.js:134:20)
    at Decoder.add (/home/madara/projects/jasmine-benchmark-testing/node_modules/karma/node_modules/socket.io/node_modules/socket.io-parser/index.js:247:12)
```

I'm running only this test.
Under different reporters, the test works fine, and fails correctly when I change the expected values.

**Comment by MadaraUchiha** [comment]
PEBKAC.

**Comment by ChristophVitz-ItSonix** [comment]
What exactly was the issue? I have the same error.

**Comment by MadaraUchiha** [comment]
It was 9 months ago, I'm afraid I don't remember. Sorry :disappointed:
